#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>

int Collatz(int n){ /// This function allows for the Collatz Sequence of a number to be generated by taking in any number n

    printf("%d ",n); /// the number is then printed
    if(n==1) /// if n is one then it is returned
        return 1;
    else{
	if(n % 2 == 0) //else if the remainder of n divided by 2 is 0, then the function is called again with n divided by 2
		return Collatz(n/2);
	else /// otherwise it is called with n multiplied by 3 plus 1
		return Collatz((n*3)+1);
    }
}

int main(void){
    pid_t pid; /// a process id variable is declared
    int status,n; /// an integer for status and n are declared

    printf("Enter the number you wish to have the collatz sequence done on");
    scanf("%d",&n); /// The number you wish to find the collatz sequence for is taken

    pid = fork(); /// A child process is created and the pid is assigned a process id number

    if(pid == 0){  /// if the pid is 0, that means it is a child process
        if(n<1 || n>9){ /// if the n inputted is less than 1 or more than 9 then the code cannot be executed
            printf("Cannot be executed");
        }else{ /// otherwise it will call upon the collatz function with n
            Collatz(n);
        } 	
    }else if(pid > 0){ /// if the pid is more than 0 then it is the parent process
  	    pid = wait(&status); /// the parent will then wait until the child process finishes executing and state that it is done executing when the child is finished
	    printf("\nSequence Completed");
    }
}